services:
  php:
    build:
      context: .docker/php
      target: php
    volumes:
      - ./:/app

  composer:
    build:
      context: .docker/php
      target: composer
    volumes:
      - ./:/app

  phpunit:
    build:
      context: .docker/php
      target: phpunit
    volumes:
      - ./:/app

networks:
  basil: